print("What would you like to do?")
print("-----------")
print("Login (1)")
print("Create Account (2)")
print("-----------")
print("---Login---")
print("Enter Username: ")
print("Enter Password: ")
print("---Create Account---")
print("Enter Username: ")
print("Enter Password: ")